site_name: Palmyra
theme:
        name: 'readthedocs'
nav:
        - Getting Started : index.md
        - CRUD Reference : crud.md 
        - Data Model : concepts/datamodel.md
        - REST API : 
                - Query : rest_ref/query.md
                - Mutation : rest_ref/mutation.md
        - LifeCycle : 
                - Events : dev_ref/lifecycle.md
                - Groovy : dev_ref/groovy.md
                - Action : dev_ref/action.md
